[pytest]
markers =
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    integration: интеграционные тесты

log_cli = true
log_cli_level = INFO
log_cli_format = %(message)s
addopts = -v -s